[build]
  command = "npm run netlify-build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_BASE_URL = "https://moamen.fr"
  NEXT_PUBLIC_SITE_URL = "https://portfolio-moamen.netlify.app"

# Redirection et headers personnalisés
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; frame-src 'self' https://demo.arcade.software https://*.arcade.software; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; connect-src 'self' https://demo.arcade.software https://*.arcade.software;"

# Configuration du cache pour les assets statiques
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirection API pour les fonctions Netlify
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# On utilise le fichier _redirects pour les règles de redirection spécifiques à Next.js 